# Generated by Django 2.0.3 on 2019-02-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='extras_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='topping_flag',
            field=models.BooleanField(default=False),
        ),
    ]
