# Generated by Django 2.0.3 on 2019-02-21 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20190220_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('extras', models.CharField(max_length=256)),
                ('topping', models.CharField(max_length=256)),
                ('total', models.FloatField()),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Menu', to='orders.Menu')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='order_status',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status', to='orders.Status'),
        ),
        migrations.AddField(
            model_name='order_status',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
