# Generated by Django 2.0.3 on 2019-02-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190222_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default='1982-05-26'),
        ),
    ]
