# Generated by Django 2.2.4 on 2019-09-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190906_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='menu',
            name='photo',
            field=models.ImageField(default='food-img/None/no-img.jpg', upload_to='food-img/'),
        ),
        migrations.AlterField(
            model_name='order_status',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Done')]),
        ),
    ]
