# Generated by Django 3.2.13 on 2022-05-07 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0013_auto_20191027_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Release'), (3, 'Canceled')])),
                ('sub_total_item', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='order_status',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='order_status',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order_status',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='extras_flag',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='meal_size',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='topping_flag',
        ),
        migrations.AlterField(
            model_name='extra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In Chart'), (2, 'Paid'), (3, 'Cooking'), (4, 'Deliveried'), (5, 'Canceled')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrderUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.menu')),
                ('ingredient', models.CharField(max_length=64)),
                ('meal_size', models.PositiveSmallIntegerField(choices=[(1, 'Small'), (2, 'Large')])),
            ],
            bases=('orders.menu',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.menu')),
                ('ingredient', models.CharField(max_length=64)),
            ],
            bases=('orders.menu',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.menu')),
                ('meal_type', models.PositiveSmallIntegerField(choices=[(1, 'Regular Pizza'), (2, 'Sicilian Pizza')])),
                ('ingredient', models.CharField(max_length=64)),
                ('meal_size', models.PositiveSmallIntegerField(choices=[(1, 'Small'), (2, 'Large')])),
                ('toppings', models.ManyToManyField(related_name='PizzaMenu', to='orders.Topping')),
            ],
            bases=('orders.menu',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.menu')),
                ('ingredient', models.CharField(max_length=64)),
            ],
            bases=('orders.menu',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.menu')),
                ('ingredient', models.CharField(max_length=64)),
                ('meal_size', models.PositiveSmallIntegerField(choices=[(1, 'Small'), (2, 'Large')])),
                ('allowing_extra', models.PositiveSmallIntegerField()),
            ],
            bases=('orders.menu',),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Order_Status',
        ),
        migrations.AddField(
            model_name='chart',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chart_Menu', to='orders.menu'),
        ),
        migrations.AddField(
            model_name='chart',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='orders.order'),
        ),
        migrations.AddField(
            model_name='chart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chart_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
