# Generated by Django 3.2.13 on 2022-05-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20220507_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, related_name='PizzaMenu', to='orders.Topping'),
        ),
    ]
