# Generated by Django 3.2.13 on 2022-05-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='meal_size',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Small'), (1, 'Large')]),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='meal_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Regular Pizza'), (1, 'Sicilian Pizza')]),
        ),
    ]
