# Generated by Django 3.2.13 on 2022-05-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20220507_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='chart',
            name='extra',
            field=models.ManyToManyField(related_name='ChartExtra', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='chart',
            name='toppings',
            field=models.ManyToManyField(related_name='ChartTopping', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='amount_toppings',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0),
        ),
    ]
