# Generated by Django 3.2.13 on 2022-05-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20220507_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='allowing_extra',
        ),
    ]
