# Generated by Django 3.2.13 on 2022-05-08 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0019_remove_sub_allowing_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Release'), (2, 'Canceled')])),
                ('sub_total_item', models.DecimalField(decimal_places=2, max_digits=6)),
                ('extra', models.ManyToManyField(related_name='ChartExtra', to='orders.Topping')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chart_Menu', to='orders.menu')),
            ],
        ),
        migrations.AlterField(
            model_name='dinnerplatter',
            name='meal_size',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Small'), (1, 'Large')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'In Chart'), (1, 'Paid'), (2, 'Cooking'), (3, 'Deliveried'), (4, 'Canceled')], default=1),
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='orders.order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='toppings',
            field=models.ManyToManyField(related_name='ChartTopping', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chart_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
