# Generated by Django 3.2.13 on 2022-05-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20220508_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='meal_size',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Small'), (1, 'Large')]),
        ),
    ]
