# Generated by Django 3.2.13 on 2022-05-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_sub_meal_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_ingredient',
            field=models.CharField(default='', max_length=64),
        ),
    ]
