# Generated by Django 3.2.13 on 2022-05-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_menu_menu_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='ingredient',
        ),
    ]
