# Generated by Django 3.2.13 on 2022-05-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20220508_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_ingredient',
            new_name='ingredient',
        ),
    ]
