# Generated by Django 3.2.13 on 2022-05-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_rename_menu_ingredient_menu_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='extra',
            field=models.ManyToManyField(blank=True, null=True, related_name='ChartExtra', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, related_name='ChartTopping', to='orders.Topping'),
        ),
    ]
