# Generated by Django 3.2.13 on 2022-05-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20220508_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Release'), (2, 'Canceled')], default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sub_total_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
