# Generated by Django 3.2.13 on 2022-05-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20220508_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='extra',
            field=models.ManyToManyField(related_name='ChartExtra', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='toppings',
            field=models.ManyToManyField(related_name='ChartTopping', to='orders.Topping'),
        ),
    ]
