# Generated by Django 3.2.13 on 2022-05-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20220508_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft, in cart'), (1, 'Placed, release by client'), (2, 'Cooked'), (3, 'Deliveried'), (4, 'Canceled'), (5, 'Paid')], default=1),
        ),
    ]
