# Generated by Django 3.2.13 on 2022-05-09 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0028_auto_20220508_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='extra',
            field=models.ManyToManyField(related_name='CartExtra', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cart_Menu', to='orders.menu'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CartOrder', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='toppings',
            field=models.ManyToManyField(related_name='CartTopping', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cart_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft, in cart'), (1, 'Placed, release by client'), (2, 'Cooked'), (3, 'Deliveried'), (4, 'Canceled'), (5, 'Paid')], default=0),
        ),
    ]
